// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0o7NsoeCy2zx4x52CoZeohuimgbLTTs',
    appId: '1:49382995294:web:debb0dd62268b00f0acbcf',
    messagingSenderId: '49382995294',
    projectId: 'verygoodproblemsolver',
    authDomain: 'verygoodproblemsolver.firebaseapp.com',
    storageBucket: 'verygoodproblemsolver.appspot.com',
    measurementId: 'G-EGG4WEN166',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHidPNBK-LW_ZXSQ6Tm198M-p8R2Tv14',
    appId: '1:49382995294:android:f456e990392e7ce00acbcf',
    messagingSenderId: '49382995294',
    projectId: 'verygoodproblemsolver',
    storageBucket: 'verygoodproblemsolver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcEoIa_BhHnFRaFTWXioQFWF7J3SoXihE',
    appId: '1:49382995294:ios:a23ac4fa397c49a90acbcf',
    messagingSenderId: '49382995294',
    projectId: 'verygoodproblemsolver',
    storageBucket: 'verygoodproblemsolver.appspot.com',
    iosClientId: '49382995294-rjq6tnnh2l3hadtc097vs6cpd86e76pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeAdvice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcEoIa_BhHnFRaFTWXioQFWF7J3SoXihE',
    appId: '1:49382995294:ios:714a30c52f3734cb0acbcf',
    messagingSenderId: '49382995294',
    projectId: 'verygoodproblemsolver',
    storageBucket: 'verygoodproblemsolver.appspot.com',
    iosClientId: '49382995294-a67psptb799sj05o4l2rdjlannvuvktg.apps.googleusercontent.com',
    iosBundleId: 'problems.creativename64.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0o7NsoeCy2zx4x52CoZeohuimgbLTTs',
    appId: '1:49382995294:web:9424b2a4dd15546a0acbcf',
    messagingSenderId: '49382995294',
    projectId: 'verygoodproblemsolver',
    authDomain: 'verygoodproblemsolver.firebaseapp.com',
    storageBucket: 'verygoodproblemsolver.appspot.com',
    measurementId: 'G-PMZC56646B',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBr0o7NsoeCy2zx4x52CoZeohuimgbLTTs',
    appId: '1:49382995294:web:a07ccbce08bd757b0acbcf',
    messagingSenderId: '49382995294',
    projectId: 'verygoodproblemsolver',
    authDomain: 'verygoodproblemsolver.firebaseapp.com',
    storageBucket: 'verygoodproblemsolver.appspot.com',
    measurementId: 'G-F8ESFRF6RZ',
  );
}
